### ISSUE TITLE
Out of prize error

### ISSUE THREAD

**Issue by crymates** [me4502/SlotMachines#10]
Using `spongeforge-1.11.2-2227-6.0.0-BETA-2224` getting "Out of prize" error also when the owner has enough money. There needs to be an error handling the balance of an player.
Using the `EconomyLite-6.0.0-2.10.2-19` (latest build) economy plugin.

![2017-03-07_20 58 33](https://cloud.githubusercontent.com/assets/22519816/23675315/3ed7ddb0-0379-11e7-88aa-5492ac30abfb.png)

**Comment by me4502** [comment]
If you're using the default config, the owner doesn't have enough money. They need enough money to be able to pay out the maximum prize, which is by default 1366 times the payment price.

**Comment by crymates** [comment]
Good to know, thx alot!
