### ISSUE TITLE
Out of Money

### ISSUE THREAD

**Issue by tyler489** [me4502/SlotMachines#13]
Player Set the limit of the machine to payout 2500$ and they have 50k$ using defaults but it says player out of money
Ah... The player has to have the amount to pay out Max payout even if machine is limited.... Can this be changed so players only have to have the Limit of the machine or more?

**Comment by me4502** [comment]
The limit on the machine is the minimum limit, as in how low the other players money can go.

The other number is the price to play, which is multiplied by the factor payout and the tier payout to give the winnings. You have to have atleast enough to pay the maximum to play. Eg, I think default maximum is 1666x. 

Just saw the edit. Doing so would mean that you’d get cases where the player would win more than the owner could pay out, so they wouldn’t get their full winnings.

**Comment by tyler489** [comment]
The bottom line is the max # a machine will pay correct?

**Comment by tyler489** [comment]
Ohhhhhhhh i seee nm
