### ISSUE TITLE
It seems the plugin is not working: out-of-money

### ISSUE THREAD

**Issue by ziceptor** [me4502/SlotMachines#3]
Always out-of-money. Price 100.0, limit 0.0.
Frames something should be displayed? Lamp also does not illuminate. The balance of the player is not changed. 

forge-1.11.2-13.20.0.2201-universal.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2023.jar
SlotMachines (latest from ore and github)

**Comment by me4502** [comment]
This isn't an issue - see FAQ on Ore page, https://ore.spongepowered.org/me4502/SlotMachines

**Comment by ziceptor** [comment]
I'm not sure. I think the balance was great. I'll check it out.
